searchCriteria: # For integer values, set as 0 to not include/ignore as a parameter
  postcode: Insert Postcode Here
  distance: 50 # Measured in miles. 
  make: any
  priceMin: 0
  priceMax: 2000 
  yearMin: 1990
  yearMax: 0
  transmission: automatic  # Accepted values: auto, manual or any
  mileage: 0 
sites:
  autotrader: true
  gumtree: false
  ebay: true
notifications:
  pushover: 
    enabled: false
    userKey: your_key_here
    apiKey: your_key_here
  windows: true
